name: Build Xamarin App

on: [ push ]

env:
  openApiToken: ${{ secrets.OPENAITOKEN }}
  
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set default Xamarin SDK versions
        run: |
          $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --android=13.0
      - name: Setup .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install dependencies
        run: nuget restore XamarinDemo2.sln
      - name: Run Unit Tests
        run: cd UnitTest && dotnet test && cd ..
  
  build-android:
    needs: test
    runs-on: macos-latest
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      - name: Set default Xamarin SDK versions
        run: |
          $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --android=13.0

      - name: Setup .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install dependencies
        run: nuget restore XamarinDemo2.sln

      - name: Decode keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'AIWorkoutKeystore'
          fileDir: './XamarinDemo2/XamarinDemo2.Android'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Build
        run: |
          cd XamarinDemo2/XamarinDemo2.Android && msbuild XamarinDemo2.Android.csproj /t:PackageForAndroid /t:SignAndroidPackage /p:Configuration=Release
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: XamarinDemo2/XamarinDemo2.Android/bin/Release/com.companyname.xamarindemo2-Signed.apk
  
  build-ios:
    needs: test
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
#      - name: Set default Xamarin SDK versions
#        run: |
#          ls -l /Library/Frameworks/Xamarin.iOS.framework/Versions
#          $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --ios=16.2
#          
#      - name: Setup .NET Core SDK 7.0.x
#        uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: '7.0.x'
#          
#      - name: Install dependencies
#        run: nuget restore XamarinDemo2.sln

      - uses: bradyjoslin/xamarinios-signedbuild-action@v1
        name: Build iOS
        with:
          csproj_path: ./XamarinDemo2/XamarinDemo2.iOS/XamarinDemo2.iOS.csproj
          mobileprovision: ${{ secrets.MOBILEPROVISION }}
          cert_p12: ${{ secrets.CERT_P12 }}
          p12_pass: ${{ secrets.P12_PASS }}
          configuration: "Release"
      
  upload-android:
    needs: build-android
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        name: Check out repo
    
      - name: Download a build artifact
        uses: actions/download-artifact@v2
        with:
          name: app
  
      - name: Upload artifact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: anavarromartin/AIWorkout
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Collaborators
          file: com.companyname.xamarindemo2-Signed.apk
          notifyTesters: true
          debug: true
          gitReleaseNotes: true
          
