name: Build Xamarin.Android app

on: [ push ]

jobs:
  build:

    runs-on: macos-latest

    env:
      openApiToken: ${{ secrets.OPENAITOKEN }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      - name: Set default Xamarin SDK versions
        run: |
          $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --android=13.0

      - name: Setup .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install dependencies
        run: nuget restore XamarinDemo2.sln

      - name: Run Unit Tests
        run: cd UnitTest && dotnet test && cd ..
        
      - name: Decode keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: AIWorkoutKeystore
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Build
        run: |
          cd XamarinDemo2/XamarinDemo2.Android && msbuild XamarinDemo2.Android.csproj /t:PackageForAndroid /t:SignAndroidPackage /p:Configuration=Release
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: XamarinDemo2/XamarinDemo2.Android/bin/Release/com.companyname.xamarindemo2-Signed.apk
          
  upload:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        name: Check out repo
    
      - name: Download a build artifact
        uses: actions/download-artifact@v2
        with:
          name: app
  
      - name: Upload artifact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: anavarromartin/AIWorkout
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Collaborators
          file: com.companyname.xamarindemo2-Signed.apk
          notifyTesters: true
          debug: true
          gitReleaseNotes: true
          
